### ISSUE TITLE
Not working with NumPy 1.20.1

### ISSUE THREAD

**Issue by shankhya** [philgyford/python-halftone#5]
I tried halftoning an image using Halftone.py using python halftone.py -l Banff.jpg (-l command for halftoning the images) but the following errors occurred 

(Haltone) C:\Users\shank\Documents\Documents\Haltone>python halftone.py -l Banff.jpg
Traceback (most recent call last):
  File "halftone.py", line 219, in <module>
    CMYK = halftone(CMYK, args.size, args.angles, args.fill, args.sharpness)
  File "halftone.py", line 111, in halftone
    tiled_kernel = np.tile(kernel, num_kernels)
  File "<__array_function__ internals>", line 5, in tile
  File "C:\Users\shank\anaconda3\envs\Haltone\lib\site-packages\numpy\lib\shape_base.py", line 1260, in tile
    return c.reshape(shape_out)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

If I do not use the -l command, then the resultant images are not halftoned. 

Please help me solve this issue. 

Thanks,
Shankhya.

**Comment by philgyford** [comment]
Hi Shankya - I'm stumped I'm afraid. The code doesn't require numpy, but I don't know enough (anything) about numpy to know what the issue might be. I can only say it works for me on a Mac - I don't have a Windows machine to try it on.
