### ISSUE TITLE
angles=[45] form README.md (description for github) throws an error

### ISSUE THREAD

**Issue by Rel-Oiv** [philgyford/python-halftone#8]
Hello,

The line of code `im.make(style="grayscale", angles=[45])` mentioned in the description of the github pages throws an error when is executed:
```
File "H:\2.Stuff\Projects\Script to execute image combination\steicPythonScript\venv\halftone2.py", line 139, in check_arguments raise ValueError(
ValueError: The angles argument must be a list of 4 integers, but it has 1.
```

I tried the function with angles=[45, 45, 45, 45] and it executed without errors

**Comment by philgyford** [comment]
Sorry about that - it now accepts a list with a single element if you're using `style="grayscale"`.
