### ISSUE TITLE
An error I cannot shake off: 

### ISSUE THREAD

**Issue by TudorBirlea** [philgyford/python-halftone#9]
h = halftone.Halftone("/path/to/myimage.jpg")
AttributeError: module 'halftone' has no attribute 'Halftone'. Did you mean: 'halftone'?

This error comes up when running: 

import halftone

h = halftone.Halftone("/path/to/myimage.jpg")
h.make()

**Comment by philgyford** [comment]
Strange, it seems to work for me:

```shell
➜ python
Python 3.8.18 (default, Dec  8 2023, 16:39:28) 
[Clang 15.0.0 (clang-1500.0.40.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import halftone
>>> h = halftone.Halftone("/Users/phil/Desktop/_testpics/kittens.jpg")
>>> h.make()
>>> 
```

Cute evidence:

![kittens_halftoned](https://github.com/philgyford/python-halftone/assets/66670/40449d57-15a7-48b9-bf62-fcb8cf0e49b4)

**Comment by TudorBirlea** [comment]
<img width="688" alt="Screenshot 2024-03-05 at 18 31 57" src="https://github.com/philgyford/python-halftone/assets/99736044/6d97f31c-9d86-4a29-b138-666354178106">

I don't know if this helps. I'm a beginner so I'm pretty much stuck here. Anyway, I appreciate your quick reply. Thank you.

**Comment by philgyford** [comment]
Is your `hftttn.py` file in the same directory as `halftone.py`?

**Comment by TudorBirlea** [comment]
![pic_halftoned](https://github.com/philgyford/python-halftone/assets/99736044/bd45b376-07ff-44d1-aa81-0e678c9bf2b1)

My bad, you're right, was in the wrong folder, now it works.

**Comment by philgyford** [comment]
Well done!
